rootProject.name = "policy-hub"
include("validation")
include("test-utils")
include("policy_evaluation")
include("policy_evaluation:edc_extension_storage")
include("policy_evaluation:edc_extension_storage:IsDataspaceMember")
include("policy_evaluation:edc_extension_storage:AccessPolicy")
include("policy_evaluation:edc_extension_storage:LocationPolicy")
include("policy_evaluation:edc_extension_storage:BillingPolicy")
include("policy_evaluation:edc_extension_storage:TimeFramePolicy")